export enum ErrorCode {
  // Auth errors
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_VERIFICATION_LINK = 'INVALID_VERIFICATION_LINK',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  VERIFICATION_EMAIL_RATE_LIMITED = 'VERIFICATION_EMAIL_RATE_LIMITED',
  EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',

  // User errors
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Resource errors
  GALLOP_NOT_FOUND = 'GALLOP_NOT_FOUND',
  KNOWLEDGE_NOT_FOUND = 'KNOWLEDGE_NOT_FOUND',
  RECEIPT_NOT_FOUND = 'RECEIPT_NOT_FOUND',
  PACK_NOT_FOUND = 'PACK_NOT_FOUND',
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',

  // File errors
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',

  // Stripe errors
  INVALID_PRICE = 'INVALID_PRICE',
  STRIPE_SESSION_ERROR = 'STRIPE_SESSION_ERROR',
  PAYMENT_NOT_VERIFIED = 'PAYMENT_NOT_VERIFIED',

  // Clubhouse errors
  CLUBHOUSE_DAILY_ALREADY_ANSWERED = 'CLUBHOUSE_DAILY_ALREADY_ANSWERED',

  // Generic errors
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
